// Code generated by Slice Machine. DO NOT EDIT.

import ProfileCard from './ProfileCard/index.svelte';
import Test from './Test/index.svelte';
import TextBlockMain from './TextBlockMain/index.svelte';

export const components = {
	profile_card: ProfileCard,
	test: Test,
	text_block_main: TextBlockMain
};
