// Code generated by Slice Machine. DO NOT EDIT.

import Test from './Test/index.svelte';
import TextBlockMain from './TextBlockMain/index.svelte';

export const components = {
	test: Test,
	text_block_main: TextBlockMain
};
